---
name: Module-Bundled-Files
version: 0.03
author:
  - Paul Campbell <kemitix@gmail.com>
abstract: Access files bundled with Module
license: perl
requires:
  Class::ISA: 0
  File::Spec: 0
  Module::Build: 0.26
  Test::More: 0
provides:
  Module::Bundled::Files:
    file: lib/Module/Bundled/Files.pm
    version: 0.03
generated_by: Module::Build version 0.26
